sudo: false
language: python
cache: pip
python: 3.5
script: true
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: dbogdanov
  distributions: sdist bdist_wheel
  password:
    secure: 4M7A1uxjdAmkyR6LrLsJcQIxN5xQiLK33hiTQO9jU3sUIO0aqxVK7OWSMuepG0TW+D1tV+8nMWPCFsXrW/ibrFBzhbRKOOW7FK8YreaA/Iat494qW4EtPWk2eXgCSMoioSzi4K3EPvYNfaIjkzqAlxUfJsACrBI70YdL7VRjfyo=
  on:
    branch: master
